// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Thankyou note field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.thankyou_note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  thankyou_note: prismic.RichTextField;

  /**
   * Sign up text field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.sign_up_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sign_up_text: prismic.RichTextField;

  /**
   * Social media text field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  social_media_text: prismic.RichTextField;

  /**
   * Email Address field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  email_address: prismic.RichTextField;

  /**
   * Instagram Icon field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  instagram_icon: prismic.ImageField<never>;

  /**
   * Facebook Icon field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facebook_icon: prismic.ImageField<never>;

  /**
   * LinkedIn field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  linkedin: prismic.ImageField<never>;

  /**
   * Twitter Icon field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.twitter_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  twitter_icon: prismic.ImageField<never>;

  /**
   * Copyright text field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text: prismic.RichTextField;

  /**
   * Term and conditions field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.term_and_conditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  term_and_conditions: prismic.RichTextField;

  /**
   * Copyright text centre field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_text_centre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text_centre: prismic.RichTextField;

  /**
   * Arrow vector field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.arrow_vector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  arrow_vector: prismic.ImageField<never>;

  /**
   * Line vector field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.line_vector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  line_vector: prismic.ImageField<never>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | Section7Slice
  | MediaHighlightCardSlice
  | StartJourneySlice
  | FeatureCardGridSlice
  | CategoryCardsGridSlice
  | Section2Slice
  | HeroSlice;

/**
 * Content for landing page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Menu field in *Navbar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  menu: prismic.RichTextField;

  /**
   * Cyclesphere field in *Navbar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.cyclesphere
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cyclesphere: prismic.RichTextField;

  /**
   * Get Started field in *Navbar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.get_started
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  get_started: prismic.RichTextField;

  /**
   * Forward Arrow field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.forward_arrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  forward_arrow: prismic.ImageField<never>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | SpacerSlice
  | ContactFormImageSideSlice
  | FeatureBannerHighlightedCtaSlice
  | GalleryWithHighlightedQuoteSlice
  | TestimonialCardSlice
  | HeroBannerSlice
  | TestimonialHighlightSlice
  | IconCardsWithTeamSlice
  | CtaImageCardSlice
  | HeroWithNavbarSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | LandingPageDocument
  | NavbarDocument
  | PageDocument;

/**
 * Item in *CategoryCardsGrid → Default → Primary → Button*
 */
export interface CategoryCardsGridSliceDefaultPrimaryButtonItem {
  /**
   * Join now field in *CategoryCardsGrid → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.button[].join_now
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  join_now: prismic.KeyTextField;

  /**
   * north east arrow field in *CategoryCardsGrid → Default → Primary → Button*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.button[].north_east_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  north_east_arrow: prismic.ImageField<never>;
}

/**
 * Item in *CategoryCardsGrid → Default → Primary → Cards*
 */
export interface CategoryCardsGridSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *CategoryCardsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CategoryCardsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CategoryCardsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Color field in *CategoryCardsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Button field in *CategoryCardsGrid → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *CategoryCardsGrid → Default → Primary*
 */
export interface CategoryCardsGridSliceDefaultPrimary {
  /**
   * Category field in *CategoryCardsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  category: prismic.RichTextField;

  /**
   * description field in *CategoryCardsGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *CategoryCardsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<
    Simplify<CategoryCardsGridSliceDefaultPrimaryButtonItem>
  >;

  /**
   * Cards field in *CategoryCardsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category_cards_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<CategoryCardsGridSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for CategoryCardsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a flexible grid of category/feature cards, each with an optional image, title, description, background color, and CTA button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryCardsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoryCardsGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategoryCardsGrid*
 */
type CategoryCardsGridSliceVariation = CategoryCardsGridSliceDefault;

/**
 * CategoryCardsGrid Shared Slice
 *
 * - **API ID**: `category_cards_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryCardsGridSlice = prismic.SharedSlice<
  "category_cards_grid",
  CategoryCardsGridSliceVariation
>;

/**
 * Primary content in *ContactFormImageSide → Form with Side Image → Primary*
 */
export interface ContactFormImageSideSliceFormWithSideImagePrimary {
  /**
   * Form Title field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * Form Description field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.form_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_description: prismic.RichTextField;

  /**
   * Name label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField;

  /**
   * First Name Label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.first_name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_name_label: prismic.KeyTextField;

  /**
   * Last Name Label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.last_name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_name_label: prismic.KeyTextField;

  /**
   * Email Label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Message Label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField;

  /**
   * Submit Button Label field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.submit_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_label: prismic.KeyTextField;

  /**
   * Side Image field in *ContactFormImageSide → Form with Side Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_image_side.form_with_side_image.primary.side_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  side_image: prismic.ImageField<never>;
}

/**
 * Form with Side Image variation for ContactFormImageSide Slice
 *
 * - **API ID**: `form_with_side_image`
 * - **Description**: This variation presents a contact form alongside a visually highlighted image, ideal for layouts where imagery is as important as the form itself.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormImageSideSliceFormWithSideImage =
  prismic.SharedSliceVariation<
    "form_with_side_image",
    Simplify<ContactFormImageSideSliceFormWithSideImagePrimary>,
    never
  >;

/**
 * Slice variation for *ContactFormImageSide*
 */
type ContactFormImageSideSliceVariation =
  ContactFormImageSideSliceFormWithSideImage;

/**
 * ContactFormImageSide Shared Slice
 *
 * - **API ID**: `contact_form_image_side`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormImageSideSlice = prismic.SharedSlice<
  "contact_form_image_side",
  ContactFormImageSideSliceVariation
>;

/**
 * Primary content in *CtaImageCard → Default → Primary*
 */
export interface CtaImageCardSliceDefaultPrimary {
  /**
   * Title field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Main Image field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Subtitle field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * bar image field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.bar_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bar_image: prismic.ImageField<never>;

  /**
   * Subtitle description field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.subtitle_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle_description: prismic.RichTextField;

  /**
   * CTA Button field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Cross image field in *CtaImageCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_image_card.default.primary.cross_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cross_image: prismic.ImageField<never>;
}

/**
 * Default variation for CtaImageCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: A card with image, optional close button, content area, and a single call-to-action button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaImageCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaImageCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaImageCard*
 */
type CtaImageCardSliceVariation = CtaImageCardSliceDefault;

/**
 * CtaImageCard Shared Slice
 *
 * - **API ID**: `cta_image_card`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaImageCardSlice = prismic.SharedSlice<
  "cta_image_card",
  CtaImageCardSliceVariation
>;

/**
 * Item in *FeatureBannerHighlightedCta → Default → Primary → CTA Group*
 */
export interface FeatureBannerHighlightedCtaSliceDefaultPrimaryCtaGroupItem {
  /**
   * CTA Leading Text field in *FeatureBannerHighlightedCta → Default → Primary → CTA Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.cta_group[].cta_leading_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_leading_text: prismic.KeyTextField;

  /**
   * CTA Highlighted Text field in *FeatureBannerHighlightedCta → Default → Primary → CTA Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.cta_group[].cta_highlighted_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_highlighted_text: prismic.KeyTextField;

  /**
   * CTA Link field in *FeatureBannerHighlightedCta → Default → Primary → CTA Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.cta_group[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FeatureBannerHighlightedCta → Default → Primary*
 */
export interface FeatureBannerHighlightedCtaSliceDefaultPrimary {
  /**
   * Main Image field in *FeatureBannerHighlightedCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Headline field in *FeatureBannerHighlightedCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subheadline field in *FeatureBannerHighlightedCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheadline: prismic.RichTextField;

  /**
   * CTA Group field in *FeatureBannerHighlightedCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.cta_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta_group: prismic.GroupField<
    Simplify<FeatureBannerHighlightedCtaSliceDefaultPrimaryCtaGroupItem>
  >;

  /**
   * Supporting Image field in *FeatureBannerHighlightedCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_banner_highlighted_cta.default.primary.supporting_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  supporting_image: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureBannerHighlightedCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Full-width feature banner with main image background, textual content overlay (headline, subheadline), prominent CTA with split style, and optional secondary image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureBannerHighlightedCtaSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FeatureBannerHighlightedCtaSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *FeatureBannerHighlightedCta*
 */
type FeatureBannerHighlightedCtaSliceVariation =
  FeatureBannerHighlightedCtaSliceDefault;

/**
 * FeatureBannerHighlightedCta Shared Slice
 *
 * - **API ID**: `feature_banner_highlighted_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureBannerHighlightedCtaSlice = prismic.SharedSlice<
  "feature_banner_highlighted_cta",
  FeatureBannerHighlightedCtaSliceVariation
>;

/**
 * Item in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
 */
export interface FeatureCardGridSliceDefaultCardsPrimaryFeatureCardsItem {
  /**
   * Emblem Image field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].emblem_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  emblem_image: prismic.ImageField<never>;

  /**
   * Card Title field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Card Subtitle field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Card Description field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Card Call To Action field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].card_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  card_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Card Background Color field in *FeatureCardGrid → Default Cards Grid → Primary → Feature Cards*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Primary content in *FeatureCardGrid → Default Cards Grid → Primary*
 */
export interface FeatureCardGridSliceDefaultCardsPrimary {
  /**
   * Section Title field in *FeatureCardGrid → Default Cards Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.header_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  header_title: prismic.RichTextField;

  /**
   * Section Description field in *FeatureCardGrid → Default Cards Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.header_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  header_description: prismic.RichTextField;

  /**
   * Section Call To Action field in *FeatureCardGrid → Default Cards Grid → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.header_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Feature Cards field in *FeatureCardGrid → Default Cards Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_card_grid.default_cards.primary.feature_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_cards: prismic.GroupField<
    Simplify<FeatureCardGridSliceDefaultCardsPrimaryFeatureCardsItem>
  >;
}

/**
 * Default Cards Grid variation for FeatureCardGrid Slice
 *
 * - **API ID**: `default_cards`
 * - **Description**: Displays a grid of feature or category cards, each with structured content, and an optional section header and call-to-action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureCardGridSliceDefaultCards = prismic.SharedSliceVariation<
  "default_cards",
  Simplify<FeatureCardGridSliceDefaultCardsPrimary>,
  never
>;

/**
 * Slice variation for *FeatureCardGrid*
 */
type FeatureCardGridSliceVariation = FeatureCardGridSliceDefaultCards;

/**
 * FeatureCardGrid Shared Slice
 *
 * - **API ID**: `feature_card_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureCardGridSlice = prismic.SharedSlice<
  "feature_card_grid",
  FeatureCardGridSliceVariation
>;

/**
 * Item in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary → Gallery Images*
 */
export interface GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimaryGalleryImagesItem {
  /**
   * Image field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
 */
export interface GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimary {
  /**
   * Section Title field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Section Description field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Gallery Images field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.gallery_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_images: prismic.GroupField<
    Simplify<GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimaryGalleryImagesItem>
  >;

  /**
   * inverted commas field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.inverted_commas
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  inverted_commas: prismic.ImageField<never>;

  /**
   * Highlighted Quote field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.highlighted_quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlighted_quote: prismic.RichTextField;

  /**
   * Call to Action Button field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * north east arrow field in *GalleryWithHighlightedQuote → Gallery with Highlighted Quote → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_with_highlighted_quote.default_with_quote.primary.north_east_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  north_east_arrow: prismic.ImageField<never>;
}

/**
 * Gallery with Highlighted Quote variation for GalleryWithHighlightedQuote Slice
 *
 * - **API ID**: `default_with_quote`
 * - **Description**: Displays a responsive image gallery and prominently features a quote or message with an optional call-to-action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryWithHighlightedQuoteSliceDefaultWithQuote =
  prismic.SharedSliceVariation<
    "default_with_quote",
    Simplify<GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimary>,
    never
  >;

/**
 * Slice variation for *GalleryWithHighlightedQuote*
 */
type GalleryWithHighlightedQuoteSliceVariation =
  GalleryWithHighlightedQuoteSliceDefaultWithQuote;

/**
 * GalleryWithHighlightedQuote Shared Slice
 *
 * - **API ID**: `gallery_with_highlighted_quote`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryWithHighlightedQuoteSlice = prismic.SharedSlice<
  "gallery_with_highlighted_quote",
  GalleryWithHighlightedQuoteSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading1: prismic.KeyTextField;

  /**
   * Text below heading1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text_below_heading1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_below_heading1: prismic.KeyTextField;

  /**
   * Cycle Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cycle_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cycle_image: prismic.ImageField<never>;

  /**
   * Get Started field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.get_started
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  get_started: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Learn more field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.learn_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  learn_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Heading after cycle image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading_after_cycle_image
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading_after_cycle_image: prismic.KeyTextField;

  /**
   * Text after heading2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text_after_heading2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_after_heading2: prismic.KeyTextField;

  /**
   * Cyclists Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cyclists_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cyclists_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroBanner → Headline Overlay → Primary*
 */
export interface HeroBannerSliceHeadlineOverlayPrimary {
  /**
   * Background Image field in *HeroBanner → Headline Overlay → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.headline_overlay.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Headline1 field in *HeroBanner → Headline Overlay → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.headline_overlay.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Headline2 field in *HeroBanner → Headline Overlay → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.headline_overlay.primary.headline2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline2: prismic.RichTextField;

  /**
   * Headline Background Color field in *HeroBanner → Headline Overlay → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.headline_overlay.primary.headline_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  headline_background_color: prismic.ColorField;
}

/**
 * Headline Overlay variation for HeroBanner Slice
 *
 * - **API ID**: `headline_overlay`
 * - **Description**: Hero section featuring a headline overlaid on the image background, suitable for strong calls to action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceHeadlineOverlay = prismic.SharedSliceVariation<
  "headline_overlay",
  Simplify<HeroBannerSliceHeadlineOverlayPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceHeadlineOverlay;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *HeroWithNavbar → With Text and Navbar → Primary*
 */
export interface HeroWithNavbarSliceWithTextNavbarPrimary {
  /**
   * Background Image field in *HeroWithNavbar → With Text and Navbar → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_navbar.with_text_navbar.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *HeroWithNavbar → With Text and Navbar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_navbar.with_text_navbar.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroWithNavbar → With Text and Navbar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_navbar.with_text_navbar.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Accent Text field in *HeroWithNavbar → With Text and Navbar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_navbar.with_text_navbar.primary.accent_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  accent_text: prismic.RichTextField;
}

/**
 * With Text and Navbar variation for HeroWithNavbar Slice
 *
 * - **API ID**: `with_text_navbar`
 * - **Description**: Contains prominent hero image, main heading, subheading, accent text, and navigation links at the top.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavbarSliceWithTextNavbar = prismic.SharedSliceVariation<
  "with_text_navbar",
  Simplify<HeroWithNavbarSliceWithTextNavbarPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithNavbar*
 */
type HeroWithNavbarSliceVariation = HeroWithNavbarSliceWithTextNavbar;

/**
 * HeroWithNavbar Shared Slice
 *
 * - **API ID**: `hero_with_navbar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithNavbarSlice = prismic.SharedSlice<
  "hero_with_navbar",
  HeroWithNavbarSliceVariation
>;

/**
 * Item in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Icon Cards*
 */
export interface IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryIconCardsItem {
  /**
   * Icon field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Icon Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.icon_cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Icon Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.icon_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Icon Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.icon_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Team Members*
 */
export interface IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryTeamMembersItem {
  /**
   * Photo field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_members[].photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;

  /**
   * Name field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_members[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_members[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_members[].bio
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bio: prismic.KeyTextField;
}

/**
 * Primary content in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
 */
export interface IconCardsWithTeamSliceIconCardsAndTeamGridPrimary {
  /**
   * Section Title field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Intro field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.section_intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_intro: prismic.RichTextField;

  /**
   * Icon Cards field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.icon_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  icon_cards: prismic.GroupField<
    Simplify<IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryIconCardsItem>
  >;

  /**
   * Team Section Title field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  team_section_title: prismic.RichTextField;

  /**
   * Team Section Intro field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_section_intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  team_section_intro: prismic.RichTextField;

  /**
   * Team Members field in *IconCardsWithTeam → Icon Cards With Team Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_cards_with_team.icon_cards_and_team_grid.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_members: prismic.GroupField<
    Simplify<IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryTeamMembersItem>
  >;
}

/**
 * Icon Cards With Team Grid variation for IconCardsWithTeam Slice
 *
 * - **API ID**: `icon_cards_and_team_grid`
 * - **Description**: Displays a core values section as icon cards, followed by a team member section with profile cards.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconCardsWithTeamSliceIconCardsAndTeamGrid =
  prismic.SharedSliceVariation<
    "icon_cards_and_team_grid",
    Simplify<IconCardsWithTeamSliceIconCardsAndTeamGridPrimary>,
    never
  >;

/**
 * Slice variation for *IconCardsWithTeam*
 */
type IconCardsWithTeamSliceVariation =
  IconCardsWithTeamSliceIconCardsAndTeamGrid;

/**
 * IconCardsWithTeam Shared Slice
 *
 * - **API ID**: `icon_cards_with_team`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconCardsWithTeamSlice = prismic.SharedSlice<
  "icon_cards_with_team",
  IconCardsWithTeamSliceVariation
>;

/**
 * Item in *MediaHighlightCard → Image with Highlighted Message → Primary → Text*
 */
export interface MediaHighlightCardSliceImageWithHighlightedMessagePrimaryTextItem {
  /**
   * Number field in *MediaHighlightCard → Image with Highlighted Message → Primary → Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text[].number
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  number: prismic.RichTextField;

  /**
   * Heading field in *MediaHighlightCard → Image with Highlighted Message → Primary → Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MediaHighlightCard → Image with Highlighted Message → Primary → Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Line vector field in *MediaHighlightCard → Image with Highlighted Message → Primary → Text*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text[].line_vector
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  line_vector: prismic.ImageField<never>;
}

/**
 * Primary content in *MediaHighlightCard → Image with Highlighted Message → Primary*
 */
export interface MediaHighlightCardSliceImageWithHighlightedMessagePrimary {
  /**
   * Media Image field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;

  /**
   * Highlight Title field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.highlight_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlight_title: prismic.RichTextField;

  /**
   * Highlight Description field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.highlight_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlight_description: prismic.RichTextField;

  /**
   * Button field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * north east arrow field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.north_east_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  north_east_arrow: prismic.ImageField<never>;

  /**
   * text bet images field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text_bet_images
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_bet_images: prismic.RichTextField;

  /**
   * Highlight Box Color field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.highlight_box_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  highlight_box_color: prismic.ColorField;

  /**
   * Box heading field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.box_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  box_heading: prismic.RichTextField;

  /**
   * box description field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.box_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  box_description: prismic.RichTextField;

  /**
   * Cycle Image field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.cycle_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cycle_image: prismic.ImageField<never>;

  /**
   * Text field in *MediaHighlightCard → Image with Highlighted Message → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_highlight_card.image_with_highlighted_message.primary.text[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  text: prismic.GroupField<
    Simplify<MediaHighlightCardSliceImageWithHighlightedMessagePrimaryTextItem>
  >;
}

/**
 * Image with Highlighted Message variation for MediaHighlightCard Slice
 *
 * - **API ID**: `image_with_highlighted_message`
 * - **Description**: Features an image, a standout message box for the headline, and supporting description text. Designed for emphasizing key ideas alongside a visual.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightCardSliceImageWithHighlightedMessage =
  prismic.SharedSliceVariation<
    "image_with_highlighted_message",
    Simplify<MediaHighlightCardSliceImageWithHighlightedMessagePrimary>,
    never
  >;

/**
 * Slice variation for *MediaHighlightCard*
 */
type MediaHighlightCardSliceVariation =
  MediaHighlightCardSliceImageWithHighlightedMessage;

/**
 * MediaHighlightCard Shared Slice
 *
 * - **API ID**: `media_highlight_card`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaHighlightCardSlice = prismic.SharedSlice<
  "media_highlight_card",
  MediaHighlightCardSliceVariation
>;

/**
 * Primary content in *Section2 → Default → Primary*
 */
export interface Section2SliceDefaultPrimary {
  /**
   * Backside of cycle field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.backside_of_cycle
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backside_of_cycle: prismic.ImageField<never>;

  /**
   * Main text field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.main_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_text: prismic.RichTextField;

  /**
   * Sub text field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_text: prismic.RichTextField;

  /**
   * Frontside of cycle field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.frontside_of_cycle
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  frontside_of_cycle: prismic.ImageField<never>;

  /**
   * Learn more field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.learn_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  learn_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * north east arrow field in *Section2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section2.default.primary.north_east_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  north_east_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for Section2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section2*
 */
type Section2SliceVariation = Section2SliceDefault;

/**
 * Section2 Shared Slice
 *
 * - **API ID**: `section2`
 * - **Description**: Section2
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section2Slice = prismic.SharedSlice<
  "section2",
  Section2SliceVariation
>;

/**
 * Primary content in *Section7 → Default → Primary*
 */
export interface Section7SliceDefaultPrimary {
  /**
   * Cycle Image field in *Section7 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section7.default.primary.cycle_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cycle_image: prismic.ImageField<never>;

  /**
   * Heading field in *Section7 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section7.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Section7 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section7.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Section7 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section7SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Section7SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Section7*
 */
type Section7SliceVariation = Section7SliceDefault;

/**
 * Section7 Shared Slice
 *
 * - **API ID**: `section7`
 * - **Description**: Section7
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Section7Slice = prismic.SharedSlice<
  "section7",
  Section7SliceVariation
>;

/**
 * Primary content in *Spacer → Default → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Cycle Image field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: spacer.default.primary.cycle_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cycle_image: prismic.ImageField<never>;

  /**
   * Heading field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spacer.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spacer.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: A spacer of customizable height or size.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *StartJourney → Default → Primary*
 */
export interface StartJourneySliceDefaultPrimary {
  /**
   * Heading field in *StartJourney → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: start_journey.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *StartJourney → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: start_journey.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Get Started field in *StartJourney → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: start_journey.default.primary.get_started
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  get_started: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Bicycle field in *StartJourney → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: start_journey.default.primary.bicycle
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bicycle: prismic.ImageField<never>;
}

/**
 * Default variation for StartJourney Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StartJourneySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StartJourneySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StartJourney*
 */
type StartJourneySliceVariation = StartJourneySliceDefault;

/**
 * StartJourney Shared Slice
 *
 * - **API ID**: `start_journey`
 * - **Description**: StartJourney
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StartJourneySlice = prismic.SharedSlice<
  "start_journey",
  StartJourneySliceVariation
>;

/**
 * Primary content in *TestimonialCard → With Photo and Metadata → Primary*
 */
export interface TestimonialCardSliceWithPhotoAndMetadataPrimary {
  /**
   * Heading field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * sub heading field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.sub_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_text: prismic.RichTextField;

  /**
   * Cylce Icon field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.cylce_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cylce_icon: prismic.ImageField<never>;

  /**
   * description field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Author Photo field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.author_photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_photo: prismic.ImageField<never>;

  /**
   * Author Name field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Subtitle/Metadata field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.author_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_subtitle: prismic.KeyTextField;

  /**
   * Starting comma field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.starting_comma
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  starting_comma: prismic.ImageField<never>;

  /**
   * Testimonial Text field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Ending Comma field in *TestimonialCard → With Photo and Metadata → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_card.with_photo_and_metadata.primary.ending_comma
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ending_comma: prismic.ImageField<never>;
}

/**
 * With Photo and Metadata variation for TestimonialCard Slice
 *
 * - **API ID**: `with_photo_and_metadata`
 * - **Description**: Shows a testimonial with photo, name, subtitle/metadata, and a quote. Decorative quote icons may be handled visually, not as fields.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialCardSliceWithPhotoAndMetadata =
  prismic.SharedSliceVariation<
    "with_photo_and_metadata",
    Simplify<TestimonialCardSliceWithPhotoAndMetadataPrimary>,
    never
  >;

/**
 * Slice variation for *TestimonialCard*
 */
type TestimonialCardSliceVariation = TestimonialCardSliceWithPhotoAndMetadata;

/**
 * TestimonialCard Shared Slice
 *
 * - **API ID**: `testimonial_card`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialCardSlice = prismic.SharedSlice<
  "testimonial_card",
  TestimonialCardSliceVariation
>;

/**
 * Item in *TestimonialHighlight → Default → Primary → Profiles*
 */
export interface TestimonialHighlightSliceDefaultPrimaryProfilesItem {
  /**
   * Avatar field in *TestimonialHighlight → Default → Primary → Profiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.profiles[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *TestimonialHighlight → Default → Primary → Profiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.profiles[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Caption field in *TestimonialHighlight → Default → Primary → Profiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.profiles[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Primary content in *TestimonialHighlight → Default → Primary*
 */
export interface TestimonialHighlightSliceDefaultPrimary {
  /**
   * Testimonials field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.testimonials
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials: prismic.RichTextField;

  /**
   * Profiles field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.profiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  profiles: prismic.GroupField<
    Simplify<TestimonialHighlightSliceDefaultPrimaryProfilesItem>
  >;

  /**
   * Starting comma field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.starting_comma
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  starting_comma: prismic.ImageField<never>;

  /**
   * Quote field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Ending Comma field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.ending_comma
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ending_comma: prismic.ImageField<never>;

  /**
   * Ready heading field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.ready_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ready_heading: prismic.RichTextField;

  /**
   * Description field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * north east arrow field in *TestimonialHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_highlight.default.primary.north_east_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  north_east_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for TestimonialHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays two user profiles (left and right) and a central testimonial quote, each with optional images and titles. Useful for emphasizing customer feedback with supporting author information.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialHighlight*
 */
type TestimonialHighlightSliceVariation = TestimonialHighlightSliceDefault;

/**
 * TestimonialHighlight Shared Slice
 *
 * - **API ID**: `testimonial_highlight`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialHighlightSlice = prismic.SharedSlice<
  "testimonial_highlight",
  TestimonialHighlightSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CategoryCardsGridSlice,
      CategoryCardsGridSliceDefaultPrimaryButtonItem,
      CategoryCardsGridSliceDefaultPrimaryCardsItem,
      CategoryCardsGridSliceDefaultPrimary,
      CategoryCardsGridSliceVariation,
      CategoryCardsGridSliceDefault,
      ContactFormImageSideSlice,
      ContactFormImageSideSliceFormWithSideImagePrimary,
      ContactFormImageSideSliceVariation,
      ContactFormImageSideSliceFormWithSideImage,
      CtaImageCardSlice,
      CtaImageCardSliceDefaultPrimary,
      CtaImageCardSliceVariation,
      CtaImageCardSliceDefault,
      FeatureBannerHighlightedCtaSlice,
      FeatureBannerHighlightedCtaSliceDefaultPrimaryCtaGroupItem,
      FeatureBannerHighlightedCtaSliceDefaultPrimary,
      FeatureBannerHighlightedCtaSliceVariation,
      FeatureBannerHighlightedCtaSliceDefault,
      FeatureCardGridSlice,
      FeatureCardGridSliceDefaultCardsPrimaryFeatureCardsItem,
      FeatureCardGridSliceDefaultCardsPrimary,
      FeatureCardGridSliceVariation,
      FeatureCardGridSliceDefaultCards,
      GalleryWithHighlightedQuoteSlice,
      GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimaryGalleryImagesItem,
      GalleryWithHighlightedQuoteSliceDefaultWithQuotePrimary,
      GalleryWithHighlightedQuoteSliceVariation,
      GalleryWithHighlightedQuoteSliceDefaultWithQuote,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceHeadlineOverlayPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceHeadlineOverlay,
      HeroWithNavbarSlice,
      HeroWithNavbarSliceWithTextNavbarPrimary,
      HeroWithNavbarSliceVariation,
      HeroWithNavbarSliceWithTextNavbar,
      IconCardsWithTeamSlice,
      IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryIconCardsItem,
      IconCardsWithTeamSliceIconCardsAndTeamGridPrimaryTeamMembersItem,
      IconCardsWithTeamSliceIconCardsAndTeamGridPrimary,
      IconCardsWithTeamSliceVariation,
      IconCardsWithTeamSliceIconCardsAndTeamGrid,
      MediaHighlightCardSlice,
      MediaHighlightCardSliceImageWithHighlightedMessagePrimaryTextItem,
      MediaHighlightCardSliceImageWithHighlightedMessagePrimary,
      MediaHighlightCardSliceVariation,
      MediaHighlightCardSliceImageWithHighlightedMessage,
      Section2Slice,
      Section2SliceDefaultPrimary,
      Section2SliceVariation,
      Section2SliceDefault,
      Section7Slice,
      Section7SliceDefaultPrimary,
      Section7SliceVariation,
      Section7SliceDefault,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
      StartJourneySlice,
      StartJourneySliceDefaultPrimary,
      StartJourneySliceVariation,
      StartJourneySliceDefault,
      TestimonialCardSlice,
      TestimonialCardSliceWithPhotoAndMetadataPrimary,
      TestimonialCardSliceVariation,
      TestimonialCardSliceWithPhotoAndMetadata,
      TestimonialHighlightSlice,
      TestimonialHighlightSliceDefaultPrimaryProfilesItem,
      TestimonialHighlightSliceDefaultPrimary,
      TestimonialHighlightSliceVariation,
      TestimonialHighlightSliceDefault,
    };
  }
}
