// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  category_cards_grid: dynamic(() => import("./CategoryCardsGrid")),
  cta_image_card: dynamic(() => import("./CtaImageCard")),
  feature_banner_highlighted_cta: dynamic(
    () => import("./FeatureBannerHighlightedCta"),
  ),
  feature_card_grid: dynamic(() => import("./FeatureCardGrid")),
  gallery_with_highlighted_quote: dynamic(
    () => import("./GalleryWithHighlightedQuote"),
  ),
  hero: dynamic(() => import("./Hero")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  hero_with_navbar: dynamic(() => import("./HeroWithNavbar")),
  icon_cards_with_team: dynamic(() => import("./IconCardsWithTeam")),
  media_highlight_card: dynamic(() => import("./MediaHighlightCard")),
  section2: dynamic(() => import("./Section2")),
  section7: dynamic(() => import("./Section7")),
  start_journey: dynamic(() => import("./StartJourney")),
  testimonial_card: dynamic(() => import("./TestimonialCard")),
  testimonial_highlight: dynamic(() => import("./TestimonialHighlight")),
};
