// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post: dynamic(() => import("./BlogPost")),
  category_cards_grid: dynamic(() => import("./CategoryCardsGrid")),
  contact_form_image_side: dynamic(() => import("./ContactFormImageSide")),
  cta_image_card: dynamic(() => import("./CtaImageCard")),
  feature_banner_highlighted_cta: dynamic(
    () => import("./FeatureBannerHighlightedCta"),
  ),
  feature_card_grid: dynamic(() => import("./FeatureCardGrid")),
  featured_articles_grid: dynamic(() => import("./FeaturedArticlesGrid")),
  featured_articles_grid_2: dynamic(() => import("./FeaturedArticlesGrid2")),
  gallery_with_highlighted_quote: dynamic(
    () => import("./GalleryWithHighlightedQuote"),
  ),
  hero: dynamic(() => import("./Hero")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  hero_with_navbar: dynamic(() => import("./HeroWithNavbar")),
  icon_cards_with_team: dynamic(() => import("./IconCardsWithTeam")),
  media_feed_and_leaderboard: dynamic(
    () => import("./MediaFeedAndLeaderboard"),
  ),
  media_highlight_card: dynamic(() => import("./MediaHighlightCard")),
  membership_form: dynamic(() => import("./MembershipForm")),
  news_feed_highlighted: dynamic(() => import("./NewsFeedHighlighted")),
  news_highlight_split: dynamic(() => import("./NewsHighlightSplit")),
  newsletter_optin: dynamic(() => import("./NewsletterOptin")),
  rich_content: dynamic(() => import("./RichContent")),
  rich_content_text: dynamic(() => import("./RichContentText")),
  section2: dynamic(() => import("./Section2")),
  section7: dynamic(() => import("./Section7")),
  spacer: dynamic(() => import("./Spacer")),
  start_journey: dynamic(() => import("./StartJourney")),
  testimonial_card: dynamic(() => import("./TestimonialCard")),
  testimonial_highlight: dynamic(() => import("./TestimonialHighlight")),
};
